/*
 * generated by Xtext
 */
package ${package}.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IGenerator
import org.eclipse.xtext.generator.IFileSystemAccess

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class ${name}Generator implements IGenerator {
    
    override void doGenerate(Resource resource, IFileSystemAccess fsa) {
    }
}
