/*
 * generated by Xtext
 */
package ${package};

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ${name}RuntimeModule extends ${package}.Abstract${name}RuntimeModule {

}