/*
* generated by Xtext
*/
package ${package}.ui.contentassist;

import ${package}.ui.contentassist.AbstractCrsxProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CrsxProposalProvider extends AbstractCrsxProposalProvider {

}
