/*
 * generated by Xtext
 */
package ${package}.ui.outline;

import org.eclipse.xtext.ui.editor.outline.IOutlineNode;

import ${package}.${name?lower_case}.*;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
public class ${name}OutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {
    
<#list outlineElements as outlineElement>
<#if outlineElement.leaf>
    protected boolean _isLeaf(${outlineElement.classname} element){
        return true;
    }

</#if>
<#if outlineElement.hidden>
    protected void _createNode(IOutlineNode parentNode, ${outlineElement.classname} element) {
        createChildren(parentNode,element);
    }

</#if>
</#list>
}
