/*
 * generated by Xtext
 */
package ${package}.ui.contentassist;

import ${package}.ui.contentassist.Abstract${name}ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class ${name}ProposalProvider extends Abstract${name}ProposalProvider {
}
