/*
 * generated by Xtext
 */
package ${package}.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ${name}UiModule extends ${package}.ui.Abstract${name}UiModule {
    public ${name}UiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
}
